// <auto-generated />
using CosmeticsStoreDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmeticsStoreDB.Migrations
{
    [DbContext(typeof(CosmeticsContext))]
    partial class CosmeticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmeticsStoreDB.Models.ProductModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AvailableQuantity = 10,
                            Name = "Krem do twarzy 50ml",
                            Price = 200.00m
                        },
                        new
                        {
                            ID = 2,
                            AvailableQuantity = 20,
                            Name = "Balsam do ciała 500 ml",
                            Price = 50.00m
                        },
                        new
                        {
                            ID = 3,
                            AvailableQuantity = 30,
                            Name = "Dezodorant 1szt.",
                            Price = 50.00m
                        },
                        new
                        {
                            ID = 4,
                            AvailableQuantity = 5,
                            Name = "Żel pod prysznic 750 ml",
                            Price = 20.00m
                        },
                        new
                        {
                            ID = 5,
                            AvailableQuantity = 7,
                            Name = "Odżywka do włosów 200ml",
                            Price = 30.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
